---
# tasks file for CSCfi.unity-idm

- name: Unity-idm | Install | Packages
  package: name={{ item }} state=installed
  with_items:
    - unzip
    - java-1.8.0-openjdk-headless

- name: Unity-idm | Create group | unity-idm
  group:
    name=unity-idm
    state=present
    system=yes

- name: Unity-idm | Create user | unity-idm
  user:
    name=unity-idm
    state=present
    comment=unity-idm
    createhome=no
    group=unity-idm
    home=/opt/unity
    shell=/sbin/nologin
    system=yes

- name: Unity-idm | Download | Unarchive | {{ unityidm_src }}
  unarchive:
    src: "{{ unityidm_src }}"
    dest: "/opt"
    remote_src: True
    owner: unity-idm
    creates: "{{ unityidm_home }}"

- name: Unity-idm | Templates | copy
  template: src={{ item.src }} dest={{ item.dst }}/{{ item.src }}
  with_items:
    - { src: unity-idm.service, dst: /etc/systemd/system }

- name: Unity-idm | Symlink | create | logs
  file:
    src="{{ unityidm_home }}/logs"
    dest=/var/log/unity-idm
    state=link
    force=yes

- name: Unity-idm | Symlink | create | unity-idm
  file:          
    src="{{ unityidm_home }}"
    dest=/opt/unity
    state=link
    force=yes

- name: Unity-idm | Default | Configurations
  lineinfile: dest={{ unityidm_home }}/conf/unityServer.conf regexp="^#?\s*({{ item.option }}\s*=)" backrefs=yes  line="\\1{{ item.value }}"
  with_items:
    - { option: 'unityServer.core.httpServer.advertisedHost', value: "{{ ansible_fqdn }}", state: present }
#   - { option: 'unityServer.core.httpServer.host', value: "0.0.0.0", state: present }

- name: Unity-idm | Systemd | Enable
  service: name=unity-idm enabled=yes state=started

- name: Unity-idm | Include | Tasks
  include_tasks: unityidm_mariadb.yml
